#!/usr/bin/perl -w

use Data::Dumper;

my $path = $ARGV[0];
my $message = '## This config file autogenerated by autopopulate.pl,'."\n".'## a perl script written by Stephen Andrew so shit is a lot easier.'."\n".'## You are welcome';


opendir(D, $path) || die "Can't opendir: $!\n";
my $col = 0;
my @array;
push (@array, $message);
push (@array, "\nSOUNDS = [\n");
my @temp;
while (my $f = readdir(D)) 
{
next if $f !~ /.+\.wav/;
  next if $f eq '.';
 next if $f  eq '..';
 if (!$col)
 {
  $col++;
  push(@temp, ' [');
  push(@temp, '"""');
  push(@temp, $f);
  push (@temp, '"""');
 }
 else 
 {
  push (@temp, ',');
  push (@temp, '"""');
  push (@temp, $f);
  push (@temp, '"""');
  push (@temp, ']');
  push (@temp, ',');
  push (@temp, "\n");
  $col--;
  push(@array, @temp);
  @temp = ();
 }

 
}
  closedir(D);
  push (@array, "]\n");
  print @array;